[package]
name = "ruxy-server"
version.workspace = true
edition.workspace = true

[dependencies]
nix = { version = "0.30.1", features = ["process", "term", "ioctl", "poll", "fs", "signal"] }
thiserror = "2.0.12"
